#!/bin/bash
num=0
cd $GOPATH/src/github.com/okonma-violet/
for DIR in `ls`;
do
    if [ -d $DIR/.git ];
    then
        num=$((num+1))
        echo "---------------"$num") updating \""$DIR"\"---------------";
        cd $DIR 
        #git add .
        #git commit -m 'multiple commit'
        #git push
        echo -e "\n\""$DIR"\" updated\n";
        cd ..
    else
    echo $DIR "not pass"
    fi
done

cd $GOPATH/src/
echo "---------------"$num") updating \"project\"---------------";
if [ -d project/.git ];
then
    cd project/
    #git add .
    #git commit -m 'multiple commit'
    #git push
    echo -e "\n\"project\" updated\n";
else
    echo -e "\n\"project\" dir not found\n";
fi

echo "---------------shit done---------------";